name: Go

on:
  push:
    branches: [ "main", "v1", "dev" ]
  pull_request:
    branches: [ "main", "v1", "dev" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - name: GO Env
        run: |
          go version
          go env

      - name: Build
        run: go build -v ./...

      # 运行go的单元测试
      - name: Test
        run: make test

      # 生成 codecov 覆盖报告
      - name: Test and create coverage file
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      # 上传测试覆盖率报告到 codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}